server:
    port: 9001

management:
    endpoints:
        web:
            exposure:
                include: health, info
    endpoint:
        health:
            show-details: never
    info:
        env:
            enabled: true
