FROM ubuntu/prometheus:2.33-22.04_edge
LABEL maintainer="jujin1324@daum.net"
LABEL dockerhub="https://hub.docker.com/r/ubuntu/prometheus"

EXPOSE 30090

ADD prometheus.yml /etc/prometheus/

ENV TZ UTC
