global:
    scrape_interval: 10s    # 10초 마다 Metric 을 Pulling
    evaluation_interval: 10s
scrape_configs:
    -   job_name: 'spring-monitoring-starter'
        metrics_path: '/actuator/prometheus'
        static_configs:
            -   targets: [ '192.168.0.99:9001' ]
        basic_auth:
            username: 'admin'
            password: '1234'
